# Races
Dra = ["Random", "Black Scale Dragonborn", "Blue Scale Dragonborn", "Brass Scale Dragonborn", "Bronze Scale Dragonborn", "Copper Scale Dragonborn",
      "Gold Scale Dragonborn", "Green Scale Dragonborn", "Red Scale Dragonborn", "Silver Scale Dragonborn", "White Scale Dragonborn"]
Dwf = ["Random", "Mountain Dwarf", "Hill Dwarf"]
Elf = ["Random", "Ground Elf", "High Elf" ,"Dark Elf", "Wood Elf"]
Gen = ["Random", "Air Genasi", "Earth Genasi", "Fire Genasi", "Water Genasi"]
Gno = ["Random", "Desert Gnome", "Forest Gnome", "Rock Gnome", "Svirfneblin Gnome"]
Hlf = ["Random", "Lightfoot Halfling", "Stout Halfling"]
Hum = ["Random", "Human", "Variant Human"]
race_list = ["Random", "Aarakocra", "Dragonborn", "Dwarf", "Elf", "Genasi", "Gnome", "Goliath",
        "Half-Elf", "Halfling", "Half-Orc", "Human", "Tiefling"]

# Classes
Arti = ["Alchemist Speciliast Artificer", "Armorist Speciliast Artificer",
       "Artilierist Speciliast Artificer", "Battle Smith Speciliast Artificer"]
Barb = ["Path of the Ancestral Guardian Barbarian", "Path of the Battleranger Barbarian", "Path of the Berserker Barbarian",
       "Path of the Storm Herold Barbarian", "Path of the Totem Warrior Barbarian", "Path of the Zelot Barbarian"]
Bar = ["College of Glamor Bard", "College of Lore Bard", "College of Satire Bard",
       "College of Sword Bard", "College of Valor Bard", "College of Whispers Bards"]
Cle = ["Death Domain Cleric", 'Forge Domain Cleric', "Grave Domain Cleric", "Knowledge Domain Cleric", "Life Domain Cleric", "Light Domain Cleric",
        "Nature Domain Cleric", "Order Domain Cleric", "Tempest Domain Cleric", "Trickery Domain Cleric", "War Domain Cleric", "Zeal Domain Cleric"]
Dru = ["Circle of Dreams Druid", "Circle of Land Druid",
        "Circle of the Moon Druid", "Circle of the Sheppard Druid"]
Fig = ["Arcane Archer Archetype Fighter", "Battle Master Archetype Fighter", "Cavalier Archetype Fighter",
        "Champion Archetype Fighter", "Eldrich Knight Archetype Fighter", "Samurai Archetype Fighter"]
Mon = ["Way of the Drunken Warrior Monk", "Way of the Four Elements Monk", "Way of the Kensei Monk",
        "Way of the Open Hand Monk", "Way of the Shadow Monk", "Way of the Sun Soul Monk"]
Pal = ["Oath of the Ancients Paladin", "Oath of Conquest Paladin", "Oath of the Crown Paladin",
        "Oath of Devotion Paladin", "Oath of Redemption Paladin", "Oath of Vengeance Paladin"]
Ran = ["Beast Master Archetype Ranger", "Gloom Stalker Archetype Ranger", "Horizon Walker Archetype Ranger",
        "Hunter Archetype Ranger", "Monster Slayer Archetype Ranger", "Shooting Star Archetype Ranger"]
Rog = ["Arcane Trickster Archetype Rogue", "Assassin Archetype Rogue", "Inquisitive Archetype Rogue", "Mastermind Archetype Rogue",
        "Mountebank Archetype Rogue", "Scout Archetype Rogue", "Swashbuckler Archetype Rogue", "Thief Archetype Rogue"]
Sor = ["Draconic Bloodline Origin Sorcerer", "Divine Soul Origin Sorcerer", "Phoenix Origin Sorcerer", "Sea Origin Sorcerer",
        "Shadow Origin Sorcerer", "Stone Origin Sorcerer", "Storm Origin Sorcerer", "Wild Magic Origin Sorcerer"]
War = ["Ancient Dragon Patron Warlock", "Archfey Patron Warlock", "Celestial Patron Warlock", "Fiend Patron Warlock", "Mysterious Feline Patron Warlock",
        "Great Old One Patron Warlock", "Hexblade Patron Warlock", "Queen of Spiders Patron Warlock", "Raven Queen Patron Warlock", "Serpent Patron Warlock"]
Wiz = ["Abjuration Arcane Tradition Wizard", "Conjuration Arcane Tradition Wizard", "Divination Arcane Tradition Wizard", "Evocation Arcane Tradition Wizard",
        "Illusion Arcane Tradition Wizard", "Necromancy Arcane Tradition Wizard", "Transmutation Arcane Tradition Wizard", "War Arcane Tradition Wizard"]
class_list = ["Random", 'Artificer', 'Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Monk',
                'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard']
arc_list = [[], Arti, Barb, Bar, Cle, Dru, Fig, Mon,
                Pal, Ran, Rog, Sor, War, Wiz]

# Backgrounds
bg_list = ["Random", "Acolyte", "Charlatan", "Criminal", "Entertainer", "Folk Hero",
         "Guild Artisan", "Hermit", "Noble", "Outlander", "Sage", "Sailor", "Soldier", "Urchin"]

# Acolyte
Ac_P1 = "I Idolize a particular hero of my faith, and constantly refer to that person’s deeds and example."
Ac_P2 = "I can find common ground between the fiercest enemies, empathizing with them and always working towards peace."
Ac_P3 = "I see omens in every event and action. The gods try to speak to us, we just need to listen."
Ac_P4 = "Nothing can shake my optimistic attitude."
Ac_P5 = "I quote (or misquote) sacred texts and proverbs in almost every situation."
Ac_P6 = "I am tolerant of other faiths and respect the worship of other gods."
Ac_P7 = "I have enjoyed fine food, drink, and high society among my temple’s elite. Rough living grates on me."
Ac_P8 = "I have spent so long in the temple that I have little practical experience dealing with people in the outside world."
Ac_PTR = [Ac_P1, Ac_P2, Ac_P3, Ac_P4, Ac_P5, Ac_P6, Ac_P7, Ac_P8]
Ac_I1 = "Tradition - The ancient traditions of worship and sacrifice must be upheld."
Ac_I2 = "Charity - I always try to help those in need, no matter what the personal cost."
Ac_I3 = "Change - We must help to bring about the changes the gods are constantly working in the world."
Ac_I4 = "Power - I hope to one day rise to top of my faith’s religious hierarchy."
Ac_I5 = "Faith - I trust that my deity will guide my actions. I have faith that if I work hard, things will go well."
Ac_I6 = "Aspiration - I seek to prove myself worthy of my god’s favor, by matching my actions against his or her teachings."
Ac_IDE = [Ac_I1, Ac_I2, Ac_I3, Ac_I4, Ac_I5, Ac_I6]
Ac_B1 = "I would die to recover an ancient relic of my faith that was lost long ago."
Ac_B2 = "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic."
Ac_B3 = "I owe my life to the priest who took me in when my parents died."
Ac_B4 = "Everything I do is for the common people."
Ac_B5 = "I will do anything to protect the temple where I served."
Ac_B6 = "I seek to preserve a sacred text that my enemies considered heretical and seek to destroy."
Ac_BND = [Ac_B1, Ac_B2, Ac_B3, Ac_B4, Ac_B5, Ac_B6]
Ac_F1 = "I judge others harshly, and myself even more severely."
Ac_F2 = "I put too much trust in those who wield power with my temple's hierarchy."
Ac_F3 = "My piety sometimes leads me to blindly trust those that profess faith in my god."
Ac_F4 = "I am inflexible in my thinking."
Ac_F5 = "I am suspicious of strangers and expect the worst of them."
Ac_F6 = "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life."
Ac_FLA = [Ac_F1, Ac_F2, Ac_F3, Ac_F4, Ac_F5, Ac_F6]

# Charlatan
Ch_S1 = "I cheat at games of chance."
Ch_S2 = "I shave coins or forge documents."
Ch_S3 = "I insinuate myself into people is lives to prey on their weaknesses, and secure their fortunes."
Ch_S4 = "I put on new identities like clothes."
Ch_S5 = "I run sleight-of-hand cons on street corners."
Ch_S6 = "I convince people that worthless junk is worth their hard-earned money."
Ch_SCM = [Ch_S1, Ch_S2, Ch_S3, Ch_S4, Ch_S5, Ch_S6]
Ch_P1 = "I fall in and out of love easily, and am always pursuing someone."
Ch_P2 = "I have a joke for every occasion, especially occasions where humor is inappropriate."
Ch_P3 = "Flattery is my preferred trick for getting what I want."
Ch_P4 = "I am a born gambler who cannot resist taking a risk for potential payout."
Ch_P5 = "I lie about almost everything, even when there is no good reason to."
Ch_P6 = "Sarcasm and insults are my weapons of choice."
Ch_P7 = "I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given time."
Ch_P8 = "I pocket anything I see that might have some value."
Ch_PTR = [Ch_P1, Ch_P2, Ch_P3, Ch_P4, Ch_P5, Ch_P6, Ch_P7, Ch_P8]
Ch_I1 = "Independence - I am a free spirit, no one tells me what to do."
Ch_I2 = "Fairness - I never target people who can not afford to lose a few coins."
Ch_I3 = "Charity - I distribute the money I acquire to the people who really need it."
Ch_I4 = "Creativity - I never run the same con twice."
Ch_I5 = "Friendship - Material goods come and go. Bonds of friendship last forever."
Ch_I6 = "Aspiration - I am determined to make something of myself."
Ch_IDE = [Ch_I1, Ch_I2, Ch_I3, Ch_I4, Ch_I5, Ch_I6]
Ch_B1 = "I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about."
Ch_B2 = "I owe everything to my mentor, a horrible person who is probably rotting in jail somewhere."
Ch_B3 = "Somewhere out there, I have a child who does not know me. I am making the world better for him or her."
Ch_B4 = "I come from a noble family and one day I will reclaim my lands and title from those who stole them from me."
Ch_B5 = "A powerful person killed someone I loved. Someday soon, I will have my revenge."
Ch_B6 = "I swindled and ruined a person who did not deserve it. I seek to atone for my misdeeds but might never be able to forgive myself. "
Ch_BND = [Ch_B1, Ch_B2, Ch_B3, Ch_B4, Ch_B5, Ch_B6]
Ch_F1 = "I cannot resist a pretty face."
Ch_F2 = "I am always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in."
Ch_F3 = "I am convinced that no one could ever fool me the way I fool others."
Ch_F4 = "I am too greedy for my own good. I cannot resist taking a risk if there’s money involved."
Ch_F5 = "I cannot resist swindling people who are more powerful than me."
Ch_F6 = "I hate to admit and will hate myself for it, but I will run and hide to preserve my own hide if the going gets tough."
Ch_FLA = [Ch_F1, Ch_F2, Ch_F3, Ch_F4, Ch_F5, Ch_F6]

# Criminal
Cr_S1 = "Blackmailer"
Cr_S2 = "Burglar"
Cr_S3 = "Enforcer"
Cr_S4 = "Fence"
Cr_S5 = "Highway robber"
Cr_S6 = "Hired killer"
Cr_S7 = "Pickpocket"
Cr_S8 = "Smuggler"
Cr_SPC = [Cr_S1, Cr_S2, Cr_S3, Cr_S4, Cr_S5, Cr_S6]
Cr_P1 = "I always have a plan for what to do when things go wrong."
Cr_P2 = "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me."
Cr_P3 = "The first thing I do in a new place is note the locations of everything valuable, or where such things could be hidden."
Cr_P4 = "I would rather make a new friend than a new enemy."
Cr_P5 = "I am incredibly slow to trust. Those who seem the fairest often have the most to hide."
Cr_P6 = "I do not pay attention to the risks in a situation. Never tell me the odds."
Cr_P7 = "The best way to get me to do something is to tell me I cannot do it."
Cr_P8 = "I blow up at the slightest insult."
Cr_PTR = [Cr_P1, Cr_P2, Cr_P3, Cr_P4, Cr_P5, Cr_P6, Cr_P7, Cr_P8]
Cr_I1 = "Honor - I do not steal from others in the trade."
Cr_I2 = "Freedom - Chains are meant to be broken, as are those who would forge them."
Cr_I3 = "Charity - I steal from the wealthy so that I can help people in need."
Cr_I4 = "Greed -  I will do whatever it takes to become wealthy."
Cr_I5 = "People - I am loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. "
Cr_I6 = "Redemption - There is a spark of good in everyone. "
Cr_IDE = [Cr_I1, Cr_I2, Cr_I3, Cr_I4, Cr_I5, Cr_I6]
Cr_B1 = "I am trying to pay off an old debt I owe to a generous benefactor."
Cr_B2 = "My ill-gotten gains go to support my family."
Cr_B3 = "Something important was taken from me, and I aim to steal it back."
Cr_B4 = "I will become the greatest thief that ever lived."
Cr_B5 = "I am guilty of a terrible crime. I hope I can redeem myself for it."
Cr_B6 = "Someone I loved died because of a mistake I made. That will never happen again."
Cr_BND = [Cr_B1, Cr_B2, Cr_B3, Cr_B4, Cr_B5, Cr_B6]
Cr_F1 = "When I see something valuable, I can not think about anything but how to steal it."
Cr_F2 = "When faced with a choice between money and my friends, I usually choose the money."
Cr_F3 = "If there is a plan, I will forget it. If I do not forget it, I will ignore it."
Cr_F4 = "I have a 'tell' that reveals when I am lying."
Cr_F5 = "I turn tail and run when things look bad."
Cr_F6 = "An innocent person is in prison for a crime that I committed. I am okay with that."
Cr_FLA = [Cr_F1, Cr_F2, Cr_F3, Cr_F4, Cr_F5, Cr_F6]

# Entertainer
En_S1 = "Actor"
En_S2 = "Dancer"
En_S3 = "Fire Eater"
En_S4 = "Jester"
En_S5 = "Juggler"
En_S6 = "Instrumental"
En_S7 = "Poet"
En_S8 = "Singer"
En_S9 = "Storyteller"
En_S10 = "Tumbler"
En_ROU = [En_S1, En_S2, En_S3, En_S4, En_S5, En_S6, En_S7, En_S8, En_S9, En_S10]
En_P1 = "I know a story relevant to almost every situation."
En_P2 = "Whenever I come to a new place, I collect local rumors and spread gossip."
En_P3 = "I'm a hopeless romantic, always searching for that 'special someone'."
En_P4 = "Nobody stays angry at me or around me for long, since I can defuse any amount of tension."
En_P5 = "I love a good insult, even one directed at me."
En_P6 = "I get bitter if I'm not the center of attention."
En_P7 = "I'll settle for nothing less than perfection."
En_P8 = "I change my mood or my mind as quickly as I change key in a song."
En_PTR = [En_P1, En_P2, En_P3, En_P4, En_P5, En_P6, En_P7, En_P8]
En_I1 = "Beauty - When I perform, I make the world better than it was."
En_I2 = "Tradition - The stories, legends, and songs of the past must never be forgotten, for they teach us who we are."
En_I3 = "Creativity - The world is in need of new ideas and bold action."
En_I4 = "Greed - I'm only in it for the money and fame."
En_I5 = "People - I like seeing the smiles on people's faces when I perform. That's all that matters. "
En_I6 = "Honesty - Art should reflect the soul; it should come from within and reveal who we really are. "
En_IDE = [En_I1, En_I2, En_I3, En_I4, En_I5, En_I6]
En_B1 = "My instrument is my most treasured possession, and it reminds me of someone I love."
En_B2 = "Someone stole my precious instrument, and someday I'll get it back."
En_B3 = "I want to be famous, whatever it takes."
En_B4 = "I idolize a hero of the old tales and measure my deeds against that person's."
En_B5 = "I will do anything to prove myself superior to my hated rival."
En_B6 = "I would do anything for the other members of my old troupe."
En_BND = [En_B1, En_B2, En_B3, En_B4, En_B5, En_B6]
En_F1 = "I'll do anything to win fame and renown."
En_F2 = "I'm a sucker for a pretty face."
En_F3 = "A scandal prevents me from ever going home again. That kind of trouble seems to follow me around."
En_F4 = "I once satirized a noble who still wants my head. It was a mistake that I will likely repeat."
En_F5 = "I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble."
En_F6 = "Despite my best efforts, I am unreliable to my friends."
En_FLA = [En_F1, En_F2, En_F3, En_F4, En_F5, En_F6]

# Folk Hero
Fo_S1 = "I stood up to a tyrant’s agents."
Fo_S2 = "I saved people during a natural disaster."
Fo_S3 = "I stood alone against a terrible monster."
Fo_S4 = "I stole from a corrupt merchant to help the poor."
Fo_S5 = "I led a militia to fight off an invading army."
Fo_S6 = "I broke into a tyrant’s castle and stole weapons to arm the people."
Fo_S7 = "I trained the peasantry to use farm implements as weapons against a tyrant’s soldiers."
Fo_S8 = "A lord rescinded an unpopular decree after I led a symbolic act of protest against it."
Fo_S9 = "A celestial, fey, or similar creature gave me a blessing or revealed my secret origin."
Fo_S10 = "Recruited into a lord’s army, I rose to leadership and was commended for my heroism."
Fo_DEF = [Fo_S1, Fo_S2, Fo_S3, Fo_S4, Fo_S5, Fo_S6, Fo_S7, Fo_S8, Fo_S9, Fo_S10]
Fo_P1 = "I judge people by their actions, not their words."
Fo_P2 = "If someone is in trouble, I am always ready to lend help."
Fo_P3 = "When I set my mind to something, I follow through no matter what gets in my way."
Fo_P4 = "I have a strong sense of fair play and always try to find the most equitable solution to arguments."
Fo_P5 = "I am confident in my own abilities and do what I can to instill confidence in others."
Fo_P6 = "Thinking is for other people. I prefer action."
Fo_P7 = "I misuse long words in an attempt to sound smarter."
Fo_P8 = "I get bored easily. When am I going to get on with my destiny?"
Fo_PTR = [Fo_P1, Fo_P2, Fo_P3, Fo_P4, Fo_P5, Fo_P6, Fo_P7, Fo_P8]
Fo_I1 = "Respect - People deserve to be treated with dignity and respect. "
Fo_I2 = "Fairness - No one should get preferential treatment before the law, and no one is above the law. "
Fo_I3 = "Freedom - Tyrants must not be allowed to oppress the people. "
Fo_I4 = "Might - If I become strong, I can take what I want, what I deserve."
Fo_I5 = "Sincerity - There is no good in pretending to be something I am not. "
Fo_I6 = "Destiny - Nothing and no one can steer me away from my higher calling. "
Fo_IDE = [Fo_I1, Fo_I2, Fo_I3, Fo_I4, Fo_I5, Fo_I6]
Fo_B1 = "I have a family, but I have no idea where they are. One day, I hope to see them again."
Fo_B2 = "I worked the land, I love the land, and I will protect the land."
Fo_B3 = "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter."
Fo_B4 = "My tools are symbols of my past life, and I carry them so that I will never forget my roots."
Fo_B5 = "I protect those who cannot protect themselves."
Fo_B6 = "I wish my childhood sweetheart had come with me to pursue my destiny."
Fo_BND = [Fo_B1, Fo_B2, Fo_B3, Fo_B4, Fo_B5, Fo_B6]
Fo_F1 = "The tyrant who rules my land will stop at nothing to see me killed."
Fo_F2 = "I am convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure."
Fo_F3 = "The people who knew me when I was young know my shameful secret, so I can never go home again."
Fo_F4 = "I have a weakness for the vices of the city, especially hard drink."
Fo_F5 = "Secretly, I believe that things would be better if I were a tyrant lording over the land."
Fo_F6 = "I have trouble trusting in my allies."
Fo_FLA = [Fo_F1, Fo_F2, Fo_F3, Fo_F4, Fo_F5, Fo_F6]

# Guild Artisan
Gu_S1 = "Alchemists and apothecaries"
Gu_S2 = "Armorers, locksmiths, and fine smiths"
Gu_S3 = "Brewers, distillers, and vintners"
Gu_S4 = "Calligraphers, scribes, and scriveners"
Gu_S5 = "Carpenters, roofers, and plasterers"
Gu_S6 = "Cartographers, surveyors, and chart-makers"
Gu_S7 = "Cobblers and shoemakers"
Gu_S8 = "Cooks and bakers"
Gu_S9 = "Glassblowers and glaziers"
Gu_S10 = "Jewelers and gemcutters"
Gu_S11 = "Leatherworkers, skinners, and tanners"
Gu_S12 = "Masons and stonecutters"
Gu_S13 = "Painters, limners, and sign-makers"
Gu_S14 = "Potters and tile-makers"
Gu_S15 = "Shipwrights and sailmakers"
Gu_S16 = "Smiths and metal-forgers"
Gu_S17 = "Tinkers, pewterers, and casters"
Gu_S18 = "Wagon-makers and wheelwrights"
Gu_S19 = "Weavers and dyers"
Gu_S20 = "Woodcarvers, coopers, and bowyers"
Gu_BUS = [Gu_S1, Gu_S2, Gu_S3, Gu_S4, Gu_S5, Gu_S6, Gu_S7, Gu_S8, Gu_S9, Gu_S10, Gu_S11,
        Gu_S12, Gu_S13, Gu_S14, Gu_S15, Gu_S16, Gu_S17, Gu_S18, Gu_S19, Gu_S20]
Gu_P1 = "I believe that anything worth doing is worth doing right. I ca not help it – I am a perfectionist."
Gu_P2 = "I'm a snob who looks down on those who can't appreciate fine art."
Gu_P3 = "I always want to know how things work and what makes people tick."
Gu_P4 = "I'm full of witty aphorisms and have a proverb for every occasion."
Gu_P5 = "I'm rude to people who lack my commitment to hard work and fair play."
Gu_P6 = "I like to talk at length about my profession."
Gu_P7 = "I don't part with my money easily and will haggle tirelessly to get the best deal possible."
Gu_P8 = "I'm well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven't heard of me."
Gu_PTR = [Gu_P1, Gu_P2, Gu_P3, Gu_P4, Gu_P5, Gu_P6, Gu_P7, Gu_P8]
Gu_I1 = "I'll do anything to get my hands on something rare or priceless."
Gu_I2 = "I'm quick to assume that someone is trying to cheat me."
Gu_I3 = "No one must ever learn that I once stole money from guild coffers."
Gu_I4 = "I am never satisfied with what I have – I always want more."
Gu_I5 = "I would kill to acquire a noble title."
Gu_I6 = "I'm terribly jealous of anyone who can outshine my handiwork. Everywhere I go, I'm surrounded by rivals."
Gu_IDE = [Gu_I1, Gu_I2, Gu_I3, Gu_I4, Gu_I5, Gu_I6]
Gu_B1 = "Community - It is the duty of all civilized people to strengthen the bonds of community and the security of civilization."
Gu_B2 = "Generosity - My talents were given to me so that I could use them to benefit the world. "
Gu_B3 = "Freedom - Everyone should be free to pursue his or her own livelihood. "
Gu_B4 = "Greed - I'm only in it for the money. "
Gu_B5 = "People - I'm committed to the people I care about, not to ideals. "
Gu_B6 = "Aspiration - I work hard to be the best there is at my craft."
Gu_BND = [Gu_B1, Gu_B2, Gu_B3, Gu_B4, Gu_B5, Gu_B6]
Gu_F1 = "The workshop where I learned my trade is the most important place in the world to me."
Gu_F2 = "I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy."
Gu_F3 = "I owe my guild a great debt for forging me into the person I am today."
Gu_F4 = "I pursue wealth to secure someone's love."
Gu_F5 = "One day I will return to my guild and prove that I am the greatest artisan of them all."
Gu_F6 = "I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood."
Gu_FLA = [Gu_F1, Gu_F2, Gu_F3, Gu_F4, Gu_F5, Gu_F6]

# Hermit
He_S1 = "I was searching for spiritual enlightenment."
He_S2 = "I was partaking of communal living in accordance with the dictates of a religious order."
He_S3 = "I was exiled for a crime I did not commit."
He_S4 = "I retreated from society after a life-altering event."
He_S5 = "I needed a quiet place to work on my art, literature, music, or manifesto."
He_S6 = "I needed to commune with nature, far from civilization."
He_S7 = "I was the caretaker of an ancient ruin or relic."
He_S8 = "I was a pilgrim in search of a person, place, or relic of spiritual significance."
He_SEC = [He_S1, He_S2, He_S3, He_S4, He_S5, He_S6, He_S7, He_S8]
He_P1 = "I have been isolated for so long that I speak rarely, preferring gestures and also the occasional grunt."
He_P2 = "I am utterly serene, even in the face of disaster."
He_P3 = "The leader of my community had something wise to say on every topic, and I am eager to share that wisdom."
He_P4 = "I feel tremendous empathy for all who suffer."
He_P5 = "I am oblivious to etiquette and social expectations."
He_P6 = "I connect everything that happens to me to a grand, cosmic plan."
He_P7 = "I often get lost in my own thoughts and contemplation, becoming oblivious to my surroundings."
He_P8 = "I am working on a grand philosophical theory and love sharing my ideas."
He_PTR = [He_P1, He_P2, He_P3, He_P4, He_P5, He_P6, He_P7, He_P8]
He_I1 = "Greater Good.- My gifts are meant to be shared with all, not used for my own benefit. "
He_I2 = "Logic - Emotions must not cloud our sense of what is right and true, or our logical thinking. "
He_I3 = "Free Thinking - Inquiry and curiosity are the pillars of progress. "
He_I4 = "Power - Solitude and contemplation are paths toward mystical or magical power."
He_I5 = "Live and Let Live - Meddling in the affairs of others only causes trouble."
He_I6 = "Self-Knowledge-  If you know yourself, there is nothing left to know."
He_IDE = [He_I1, He_I2, He_I3, He_I4, He_I5, He_I6]
He_B1 = "Nothing is more important than the other members of my hermitage, order, or association."
He_B2 = "I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them."
He_B3 = "I am still seeking the enlightenment I pursued in my seclusion, and it still eludes me."
He_B4 = "I entered seclusion because I loved someone I could not have."
He_B5 = "Should my discovery come to light, it could bring ruin to the world."
He_B6 = "My isolation gave me great insight into a great evil that only I can destroy."
He_BND = [He_B1, He_B2, He_B3, He_B4, He_B5, He_B6]
He_F1 = "Now that I've returned to the world, I enjoy its delights a little too much"
He_F2 = "I harbor dark, bloodthirsty thoughts that my isolation and meditation failed to quell."
He_F3 = "I am dogmatic in my thoughts and philosophy."
He_F4 = "I let my need to win arguments overshadow friendships and harmony."
He_F5 = "I would risk too much to uncover a lost bit of knowledge."
He_F6 = "I like keeping secrets and will not share them with anyone."
He_FLA = [He_F1, He_F2, He_F3, He_F4, He_F5, He_F6]

# Noble
No_P1 = "My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world."
No_P2 = "The common folk love me for my kindness and generosity."
No_P3 = "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses."
No_P4 = "I take great pains to always look my best and follow the latest fashions."
No_P5 = "I do not like to get my hands dirty, and I will not be caught dead in unsuitable accommodations."
No_P6 = "Despite my noble birth, I do not place myself above other folk. We all have the same blood."
No_P7 = "My favor, once lost, is lost forever."
No_P8 = "If you do me an injury, I will crush you, ruin your name, and salt your fields."
No_PTR = [No_P1, No_P2, No_P3, No_P4, No_P5, No_P6, No_P7, No_P8]
No_I1 = "Respect - Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity."
No_I2 = "Responsibility - It is my duty to respect the authority of those above me, just as those below me must respect mine."
No_I3 = "Independence - I must prove that I can handle myself without the coddling of my family. "
No_I4 = "Power - If I can attain more power, no one will tell me what to do. "
No_I5 = "Family - Blood runs thicker than water. "
No_I6 = "Noble Obligation -  It is my duty to protect and care for the people beneath me. "
No_IDE = [No_I1, No_I2, No_I3, No_I4, No_I5, No_I6]
No_B1 = "I will face any challenge to win the approval of my family."
No_B2 = "My house’s alliance with another noble family must be sustained at all costs."
No_B3 = "Nothing is more important than the other members of my family."
No_B4 = "I am in love with the heir of a family that my family despises."
No_B5 = "My loyalty to my sovereign is unwavering."
No_B6 = "The common folk must see me as a hero of the people."
No_BND = [No_B1, No_B2, No_B3, No_B4, No_B5, No_B6]
No_F1 = "I secretly believe that everyone is beneath me."
No_F2 = "I hide a truly scandalous secret that could ruin my family forever."
No_F3 = "I too often hear veiled insults and threats in every word addressed to me, and I am quick to anger."
No_F4 = "I have an insatiable desire for carnal pleasures."
No_F5 = "In fact, the world does revolve around me."
No_F6 = "By my words and actions, I often bring shame to my family."
No_FLA = [No_F1, No_F2, No_F3, No_F4, No_F5, No_F6]

# Outlander
Ou_S1 = "Forester"
Ou_S2 = "Trapper"
Ou_S3 = "Homesteader"
Ou_S4 = "Guide"
Ou_S5 = "Bounty hunter"
Ou_S6 = "Exile or outcast"
Ou_S7 = "Pilgrim"
Ou_S8 = "Tribal nomad"
Ou_S9 = "Hunter-gatherer"
Ou_S10 = "Tribal marauder"
Ou_ORI = [Ou_S1, Ou_S2, Ou_S3, Ou_S4, Ou_S5, Ou_S6, Ou_S7, Ou_S8, Ou_S9, Ou_S10]
Ou_P1 = "I am driven by a wanderlust that led me away from home."
Ou_P2 = "I watch over my friends as if they were a litter of newborn pups."
Ou_P3 = "I once ran twenty-five miles without stopping to warn  my clan of an approaching orc horde. I would do it again if I had to."
Ou_P4 = "I have a lesson for every situation, drawn from observing nature."
Ou_P5 = "I place no stock in wealthy or well-mannered folk. Money and manners will not save you from a hungry owlbear"
Ou_P6 = "I am always picking things up, absently fiddling with them, and sometimes accidentally breaking them."
Ou_P7 = "I feel far more comfortable around animals than people."
Ou_P8 = "I was, in fact, raised by wolves."
Ou_PTR = [Ou_P1, Ou_P2, Ou_P3, Ou_P4, Ou_P5, Ou_P6, Ou_P7, Ou_P8]
Ou_I1 = "Change - Life is like the seasons, in constant change, and we must change with it."
Ou_I2 = "Greater Good - It is each person’s responsibility to make the most happiness for the whole tribe."
Ou_I3 = "Honor - If I dishonor myself, I dishonor my whole clan."
Ou_I4 = "Might -  The strongest are meant to rule."
Ou_I5 = "Nature - The natural world is more important than all the constructs of civilization."
Ou_I6 = "Glory - I must earn glory in battle, for myself and my clan."
Ou_IDE = [Ou_I1, Ou_I2, Ou_I3, Ou_I4, Ou_I5, Ou_I6]
Ou_B1 = "My family, clan, or tribe is the most important thing in my life, even when they are far from me."
Ou_B2 = "An injury to the unspoiled wilderness of my home is an injury to me."
Ou_B3 = "I will bring terrible wrath down on the evildoers who destroyed my homeland."
Ou_B4 = "I am the last of my tribe, and it is up to me to ensure their names enter legend."
Ou_B5 = "I suffer awful visions of a coming disaster and will do anything to prevent it."
Ou_B6 = "It is my duty to provide children to sustain my tribe."
Ou_BND = [Ou_B1, Ou_B2, Ou_B3, Ou_B4, Ou_B5, Ou_B6]
Ou_F1 = "I am too enamored of ale, wine, and other intoxicants."
Ou_F2 = "There is no room for caution in a life lived to the fullest."
Ou_F3 = "I remember every insult I’ve received and nurse a silent resentment toward anyone who hass ever wronged me."
Ou_F4 = "I am slow to trust members of other races, tribes, and societies."
Ou_F5 = "Violence is my answer to almost any challenge."
Ou_F6 = "Do not expect me to save those who can’t save themselves. It is nature’s way that the strong thrive and the weak perish."
Ou_FLA = [Ou_F1, Ou_F2, Ou_F3, Ou_F4, Ou_F5, Ou_F6]

# Sage
Sa_S1 = "Alchemist"
Sa_S2 = "Astronomer"
Sa_S3 = "Discredited academic"
Sa_S4 = "Librarian"
Sa_S5 = "Professor"
Sa_S6 = "Researcher"
Sa_S7 = "Wizard's apprentice"
Sa_S8 = "Scribe"
Sa_SPE = [Sa_S1, Sa_S2, Sa_S3, Sa_S4, Sa_S5, Sa_S6, Sa_S7, Sa_S8]
Sa_P1 = "I use polysyllabic words that convey the impression of great erudition."
Sa_P2 = "I have read every book in the world's greatest libraries, or I like to boast that I have."
Sa_P3 = "I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others."
Sa_P4 = "There's nothing I like more than a good mystery."
Sa_P5 = "I'm willing to listen to every side of an argument before I make my own judgment."
Sa_P6 = "I… speak… slowly… when talking… to idiots,… which… almost… everyone… is… compared… to me."
Sa_P7 = "I am horribly, horribly awkward in social situations."
Sa_P8 = "I'm convinced that people are always trying to steal my secrets."
Sa_PTR = [Sa_P1, Sa_P2, Sa_P3, Sa_P4, Sa_P5, Sa_P6, Sa_P7, Sa_P8]
Sa_I1 = "Knowledge - The path to power and self-improvement is through knowledge."
Sa_I2 = "Beauty - What is beautiful points us beyond itself toward what is true."
Sa_I3 = "Logic - Emotions must not cloud our logical thinking."
Sa_I4 = "No Limits - Nothing should fetter the infinite possibility inherent in all existence. "
Sa_I5 = "Power - Knowledge is the path to power and domination. "
Sa_I6 = "Self-Improvement - The goal of a life of study is the betterment of oneself. "
Sa_IDE = [Sa_I1, Sa_I2, Sa_I3, Sa_I4, Sa_I5, Sa_I6]
Sa_B1 = "It is my duty to protect my students."
Sa_B2 = "I have an ancient text that holds terrible secrets that must not fall into the wrong hands."
Sa_B3 = "I work to preserve a library, university, scriptorium, or monastery."
Sa_B4 = "My life's work is a series of tomes related to a specific field of lore."
Sa_B5 = "I've been searching my whole life for the answer to a certain question."
Sa_B6 = "I sold my soul for knowledge. I hope to do great deeds and win it back."
Sa_BND = [Sa_B1, Sa_B2, Sa_B3, Sa_B4, Sa_B5, Sa_B6]
Sa_F1 = "I am easily distracted by the promise of information."
Sa_F2 = "Most people scream and run when they see a demon. I stop and take notes on its anatomy."
Sa_F3 = "Unlocking an ancient mystery is worth the price of a civilization."
Sa_F4 = "I overlook obvious solutions in favor of complicated ones."
Sa_F5 = "I speak without really thinking through my words, invariably insulting others."
Sa_F6 = "I can't keep a secret to save my life, or anyone else's."
Sa_FLA = [Sa_F1, Sa_F2, Sa_F3, Sa_F4, Sa_F5, Sa_F6]

# Sailor
Sai_P1 = "My friends know they can rely on me, no matter what."
Sai_P2 = "I work hard so that I can play hard when the work is done."
Sai_P3 = "I enjoy sailing into new ports and making new friends over a flagon of ale."
Sai_P4 = "I stretch the truth for the sake of a good story."
Sai_P5 = "To me, a tavern brawl is a nice way to get to know a new city."
Sai_P6 = "I never pass up a friendly wager."
Sai_P7 = "My language is as foul as an otyugh nest."
Sai_P8 = "I like a job well done, especially if I can convince someone else to do it."
Sai_PTR = [Sai_P1, Sai_P2, Sai_P3, Sai_P4, Sai_P5, Sai_P6, Sai_P7, Sai_P8]
Sai_I1 = "Respect - The thing that keeps a ship together is mutual respect between captain and crew"
Sai_I2 = "Fairness -  We all do the work, so we all share in the rewards."
Sai_I3 = "Freedom - The sea is freedom-the freedom to go anywhere and do anything."
Sai_I4 = "Mastery -  I'm a predator, and the other ships on the sea are my prey."
Sai_I5 = "People - I'm committed to my crewmates, not to ideals."
Sai_I6 = "Aspiration - Someday I'll own my own ship and chart my own destiny.)"
Sai_IDE = [Sai_I1, Sai_I2, Sai_I3, Sai_I4, Sai_I5, Sai_I6]
Sai_B1 = "I'm loyal to my captain first, everything else second."
Sai_B2 = "The ship is most important, crewmates and captains come and go."
Sai_B3 = "I'll always remember my first ship."
Sai_B4 = "In a harbor town, I have a paramour whose eyes nearly stole me from the sea."
Sai_B5 = "I was cheated out of my fair share of the profits, and I want to get my due."
Sai_B6 = "Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine."
Sai_BND = [Sai_B1, Sai_B2, Sai_B3, Sai_B4, Sai_B5, Sai_B6]
Sai_F1 = "I follow orders, even if I think they're wrong."
Sai_F2 = "I'll say anything to avoid having to do extra work."
Sai_F3 = "Once someone questions my courage, I never back down no matter how dangerous the situation."
Sai_F4 = "Once I start drinking, it's hard for me to stop."
Sai_F5 = "I can't help but pocket loose coins and other trinkets I come across."
Sai_F6 = "My pride will probably lead to my destruction."
Sai_FLA = [Sai_F1, Sai_F2, Sai_F3, Sai_F4, Sai_F5, Sai_F6]

# Soldier
So_S1 = "Officer"
So_S2 = "Scout"
So_S3 = "Infantry"
So_S4 = "Cavalry"
So_S5 = "Healer"
So_S6 = "Quartermaster"
So_S7 = "Standard bearer"
So_S8 = "Support staff (cook, blacksmith, or the like)"
So_SPE = [So_S1, So_S2, So_S3, So_S4, So_S5, So_S6, So_S7, So_S8]
So_P1 = "I am always polite and respectful."
So_P2 = "I am haunted by memories of war. I can't get the images of violence out of my mind."
So_P3 = "I have lost too many friends and I am slow to make a new one."
So_P4 = "I am full of inspiring and cautionary tales from my military experience which is relevant to almost every combat situation."
So_P5 = "I can stare down a hell hound without flinching."
So_P6 = "I enjoy being strong and I like breaking things."
So_P7 = "I have a crude sense of humor."
So_P8 = "I face problems head-on. A simple, direct solution is the best path to success."
So_PTR = [So_P1, So_P2, So_P3, So_P4, So_P5, So_P6, So_P7, So_P8]
So_I1 = "Greater Good - Our lot is to lay down our lives in defense of others."
So_I2 = "Responsibility - I do what I must and obey just authority."
So_I3 = "Independence - When people follow orders blindly, they embrace a kind of tyranny."
So_I4 = "Might -  In life as in war, the stronger force wins."
So_I5 = "Live and Let Live - Ideals are not worth killing over or going to war for."
So_I6 = "Nation - My city, nation, or people are all that matter."
So_IDE = [So_I1, So_I2, So_I3, So_I4, So_I5, So_I6]
So_B1 = "I would still lay down my life for the people I served with."
So_B2 = "Someone saved my life on the battlefield. To this day, I will never leave a friend behind."
So_B3 = "My honor is my life."
So_B4 = "I will never forget the crushing defeat my company suffered or the enemies who dealt it."
So_B5 = "Those who fight beside me are those worth dying for."
So_B6 = "I fight for those who cannot fight for themselves."
So_BND = [So_B1, So_B2, So_B3, So_B4, So_B5, So_B6]
So_F1 = "The monstrous enemy which we faced in battle still leaves me quivering with fear."
So_F2 = "I have little respect for anyone who is not a proven warrior."
So_F3 = "I made a terrible mistake in battle that cost many lives, and I would do anything to keep that mistake secret."
So_F4 = "My hatred of my enemies is blind and unreasoning."
So_F5 = "I obey the law, even if the law causes misery."
So_F6 = "I would rather eat my armor than admit when I’m wrong."
So_FLA = [So_F1, So_F2, So_F3, So_F4, So_F5, So_F6]

# Urchin
Ur_P1 = "I hide scraps of food and trinkets away in my pockets."
Ur_P2 = "I ask a lot of questions."
Ur_P3 = "I like to squeeze into small places where no one else can get to me."
Ur_P4 = "I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms."
Ur_P5 = "I eat like a pig and have bad manners."
Ur_P6 = "I think anyone who's nice to me is hiding evil intent."
Ur_P7 = "I don't like to bathe."
Ur_P8 = "I bluntly say what other people are hinting at or hiding."
Ur_PTR = [Ur_P1, Ur_P2, Ur_P3, Ur_P4, Ur_P5, Ur_P6, Ur_P7, Ur_P8]
Ur_I1 = "Respect - All people, rich or poor, deserve respect."
Ur_I2 = "Community: We have to take care of each other, because no one else is going to do it."
Ur_I3 = "Change - The low are lifted up, and the high and mighty are brought down. Change is the nature of things."
Ur_I4 = "Retribution - The rich need to be shown what life and death are like in the gutters."
Ur_I5 = "People - I help the people who help me-that's what keeps us alive."
Ur_I6 = "Aspiration - I'm going to prove that I'm worthy of a better life."
Ur_IDE = [Ur_I1, Ur_I2, Ur_I3, Ur_I4, Ur_I5, Ur_I6]
Ur_B1 = "My town or city is my home, and I'll fight to defend it."
Ur_B2 = "I sponsor an orphanage to keep others from enduring what I was forced to endure."
Ur_B3 = "I owe my survival to another urchin who taught me to live on the streets."
Ur_B4 = "I owe a debt I can never repay to the person who took pity on me."
Ur_B5 = "I escaped my life of poverty by robbing an important person, and I'm wanted for it."
Ur_B6 = "No one else should have to endure the hardships I've been through."
Ur_BND = [Ur_B1, Ur_B2, Ur_B3, Ur_B4, Ur_B5, Ur_B6]
Ur_F1 = "If I'm outnumbered, I will run away from a fight."
Ur_F2 = "Gold seems like a lot of money to me, and I'll do just about anything for more of it."
Ur_F3 = "I will never fully trust anyone other than myself."
Ur_F4 = "I'd rather kill someone in their sleep then fight fair."
Ur_F5 = "It's not stealing if I need it more than someone else."
Ur_F6 = "People who can't take care of themselves get what they deserve."
Ur_FLA = [Ur_F1, Ur_F2, Ur_F3, Ur_F4, Ur_F5, Ur_F6]

# Trinkets
AA = "A mummified goblin hand"
AB = "A piece of crystal that faintly glows in the moonlight"
AC = "A gold coin minted in an unknown land"
AD = "A diary written in a language you do not know"
AE = "A brass ring that never tarnishes"
AF = "An old chess piece made from glass"
AG = "A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips"
AH = "A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it"
AI = "A rope necklace from which dangles four mummified elf fingers"
AJ = "The deed for a parcel of land in a realm unknown to you"
AK = "A 1-ounce block made from an unknown material"
AL = "A small cloth doll skewered with needles"
AM = "A tooth from an unknown beast"
AN = "An enormous scale, perhaps from a dragon"
AO = "A bright green feather"
AP = "An old divination card bearing your likeness"
AQ = "A glass orb filled with moving smoke"
AR = "A 1-pound egg with a bright red shell"
AS = "A pipe that blows bubbles"
AT = "A glass jar containing a weird bit of flesh floating in pickling fluid"
AU = "A tiny gnome-crafted music box that plays a song you dimly remember from your childhood"
AV = "A small wooden statuette of a smug halfling"
AW = "A brass orb etched with strange runes"
AX = "A multicolored stone disk"
AY = "A tiny silver icon of a raven"
AZ = "A bag containing forty-seven humanoid teeth, one of which is rotten"
BA = "A shard of obsidian that always feels warm to the touch"
BB = "A dragon's bony talon hanging from a plain leather necklace"
BC = "A pair of old socks"
BD = "A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking"
BE = "A silver badge in the shape of a five-pointed star"
BF = "A knife that belonged to a relative"
BG = "A glass vial filled with nail clippings"
BH = "A rectangular metal device with two tiny metal cups on one end that throws sparks when wet"
BI = "A white, sequined glove sized for a human"
BJ = "A vest with one hundred tiny pockets"
BK = "A small, weightless stone block"
BL = "A tiny sketch portrait of a goblin"
BM = "An empty glass vial that smells of perfume when opened"
BN = "A gemstone that looks like a lump of coal when examined by anyone but you"
BO = "A scrap of cloth from an old banner"
BP = "A rank insignia from a lost legionnaire"
BQ = "A tiny silver bell without a clapper"
BR = "A mechanical canary inside a gnome-crafted lamp"
BS = "A tiny chest carved to look like it has numerous feet on the bottom"
BT = "A dead sprite inside a clear glass bottle"
BU = "A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)"
BV = "A glass orb filled with water, in which swims a clockwork goldfish"
BW = "A silver spoon with an M engraved on the handle"
BX = "A whistle made from gold-colored wood"
BY = "A dead scarab beetle the size of your hand"
BZ = "Two toy soldiers, one with a missing head"
CA = "A small box filled with different-sized buttons"
CB = "A candle that can't be lit"
CC = "A tiny cage with no door"
CD = "An old key"
CE = "An indecipherable treasure map"
CF = "A hilt from a broken sword"
CG = "A rabbit's foot"
CH = "A glass eye"
CI = "A cameo carved in the likeness of a hideous person"
CJ = "A silver skull the size of a coin"
CK = "An alabaster mask"
CL = "A pyramid of sticky black incense that smells very bad"
CM = "A nightcap that, when worn, gives you pleasant dreams"
CN = "A single caltrop made from bone"
CO = "A gold monocle frame without the lens"
CP = "A 1-inch cube, each side painted a different color"
CQ = "A crystal knob from a door"
CR = "A small packet filled with pink dust"
CS = "A fragment of a beautiful song, written as musical notes on two pieces of parchment"
CT = "A silver teardrop earring made from a real teardrop"
CU = "The shell of an egg painted with scenes of human misery in disturbing detail"
CV = "A fan that, when unfolded, shows a sleeping cat"
CW = "A set of bone pipes"
CX = "A four-leaf clover pressed inside a book discussing manners and etiquette"
CY = "A sheet of parchment upon which is drawn a complex mechanical contraption"
CZ = "An ornate scabbard that fits no blade you have found so far"
DA = "An invitation to a party where a murder happened"
DB = "A bronze pentacle with an etching of a rat's head in its center"
DC = "A purple handkerchief embroidered with the name of a powerful archmage"
DD = "Half of a floorplan for a temple, castle, or some other structure"
DE = "A bit of folded cloth that, when unfolded, turns into a stylish cap"
DF = "A receipt of deposit at a bank in a far-flung city"
DG = "A diary with seven missing pages"
DH = "An empty silver snuffbox bearing an inscription on the surface that says 'dreams'"
DI = "An iron holy symbol devoted to an unknown god"
DJ = "A book that tells the story of a legendary hero's rise and fall, with the last chapter missing"
DK = "A vial of dragon blood"
DL = "An ancient arrow of elven design"
DM = "A needle that never bend"
DN = "An ornate brooch of dwarven design"
DO = "An empty wine bottle bearing a pretty label that says, 'The Wizard of Wines Winery, Red Dragon Crush, 331422-W'"
DP = "A mosaic tile with a multicolored, glazed surface"
DQ = "A petrified mouse"
DR = "A black pirate flag adorned with a dragon's skull and crossbones"
DS = "A tiny mechanical crab or spider that moves about when it is not being observed"
DT = "A glass jar containing lard with a label that reads, 'Griffon Grease'"
DU = "A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body"
DV = "A metal urn containing the ashes of a hero"

Tri = [AA, AB, AC, AD, AE, AF, AG, AH, AI, AJ, AK, AL, AM,
       AN, AO, AP, AQ, AR, AS, AT, AU, AV, AW, AX, AY, AZ]
Trn = [BA, BB, BC, BD, BE, BF, BG, BH, BI, BJ, BK, BL, BM,
       BN, BO, BP, BQ, BR, BS, BT, BU, BV, BW, BX, BY, BZ]
Trk = [CA, CB, CC, CD, CE, CF, CG, CH, CI, CJ, CK, CL, CM,
       CN, CO, CP, CQ, CR, CS, CT, CU, CV, CW, CX, CY, CZ]
Trt = [DA, DB, DC, DD, DE, DF, DG, DH, DI, DJ, DK,
       DL, DM, DN, DO, DP, DQ, DR, DS, DT, DU, DV]